### ISSUE TITLE
Document protocol differences between Bitcoin and Namecoin.

### ISSUE THREAD

**Issue by NSkelsey** [domob1812/namecore#2]
Quite a few libraries have been written for Bitcoin, which rely on arbitrary constant parameters to make it easier for developers to port tools and projects over Namecoin's parameters ought to be documented. 

Since this is essentially another implementation of Namecoin, I think it ought to document those constants. I will collect what I learn in the comments below.

**Comment by domob1812** [comment]
I'm closing this now.  Discussion should continue somewhere else.
