### ISSUE TITLE
undefined reference to `CMerkleTx::SetMerkleBranch(CBlock const&)' in auxpow tests (No Wallet build)

### ISSUE THREAD

**Issue by JeremyRand** [domob1812/namecore#4]
Looks like the "no wallet" build configuration on Travis CI is having trouble building the auxpow tests.

    Making check in src
    make[1]: Entering directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    make[2]: Entering directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
      limiting output:
        --max-count=<n>
        --max-age=<epoch>
        --min-age=<epoch>
        --sparse
        --no-merges
        --min-parents=<n>
        --no-min-parents
        --max-parents=<n>
        --no-max-parents
        --remove-empty
        --all
        --branches
        --tags
        --remotes
        --stdin
        --quiet
      ordering output:
        --topo-order
        --date-order
        --reverse
      formatting output:
        --parents
        --children
        --objects | --objects-edge
        --unpacked
        --header | --pretty
        --abbrev=<n> | --no-abbrev
        --abbrev-commit
        --left-right
      special purpose:
        --bisect
        --bisect-vars
        --bisect-all
      CXXLD  test/test_bitcoin
    test/test_test_bitcoin-auxpow_tests.o: In function `auxpow_tests::CAuxpowBuilder::get(CTransaction const&) const':
    auxpow_tests.cpp:(.text+0x1496): undefined reference to `CMerkleTx::SetMerkleBranch(CBlock const&)'
    collect2: ld returned 1 exit status
    make[2]: *** [test/test_bitcoin] Error 1
    make[2]: Leaving directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    make[1]: *** [check-recursive] Error 1
    make[1]: Leaving directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    make: *** [check-recursive] Error 1
    travis_time:end:09145eb4:start=1420512527312109831,finish=1420512528992377282,duration=1680267451
    [0K
    [31;1mThe command "if [ "$RUN_TESTS" = "true" ]; then make check; fi" exited with 2.[0m
    travis_time:start:01d920bc
    [0K$ if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.sh; fi
    No rpc tests to run. Wallet, utils, and bitcoind must all be enabled
    travis_time:end:01d920bc:start=1420512529000104606,finish=1420512529010702513,duration=10597907
    [0K
    [32;1mThe command "if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.sh; fi" exited with 0.[0m
    travis_fold:start:after_script
    [0Ktravis_time:start:1593e274
    [0K$ {:"if [ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]; then (echo \"Upload goes here. Something like"=>"scp -r $BASE_OUTDIR server\" || echo \"upload failed\"); fi"}
    /home/travis/build.sh: line 41: scp -r /home/travis/build/JeremyRand/namecore/out server" || echo "upload failed"); fi}: No such file or directory
    travis_time:end:1593e274:start=1420512529018560808,finish=1420512529025724414,duration=7163606
    [0Ktravis_fold:end:after_script
    [0K
    Done. Your build exited with 1.

**Comment by domob1812** [comment]
This should be fixed now.  I got the same error when configuring with `--disable-wallet`, now not any more.  Please try and close the issue if it also works for you.

**Comment by JeremyRand** [comment]
I'll try this again and let you know, thanks.

**Comment by JeremyRand** [comment]
It now gets past this step in the auxpow branch, but I wasn't testing with that branch before so I'm not sure if that's a change.  Can you let me know when you've added that commit to master so I can retest there?

**Comment by domob1812** [comment]
The commit should be in both auxpow and master.

**Comment by domob1812** [comment]
Seems to be fixed now, although there are other Travis CI issues.  Closing, I'll work on the others separately.
