### ISSUE TITLE
Name "namecore" is confusing

### ISSUE THREAD

**Issue by JeremyRand** [domob1812/namecore#5]
Since Bitcore is a Javascript library, the name Namecore sounds a bit confusing.  Might be better to rename to Namecoin Core before releasing.  (Someone brought this up on IRC.)  Also, Namecoin Core will probably show up better in Google results for Namecoin.  Thoughts?

**Comment by domob1812** [comment]
We can do that, if you think it is useful.  I've never heard about Bitcore before, though, so not sure how known it is.  But Namecoin Core is fine with me.  (It isn't really used anywhere besides my forum posts, after all.  The Qt is not yet really branded to Namecoin.)

**Comment by JeremyRand** [comment]
It's particularly relevant because Ryan ported Bitcore to Namecoin a few months ago.  So yeah, I would definitely prefer to use the name Namecoin Core.

**Comment by domob1812** [comment]
We use Namecoin Core now, closing.

**Comment by JeremyRand** [comment]
The GitHub repo is still named "namecore", do we want to change that?  CC @indolering
