### ISSUE TITLE
Feature request: sendtoname

### ISSUE THREAD

**Issue by cassiniNMC** [domob1812/namecore#7]
Currently this functionality can already be achieved by a combination of two RPCs (name_show and sendtoaddress). However, the sendtoname feature could become an important "unique selling proposition" in the future. Therefore sendtoname should be an RPC in its own right, I think.

**Comment by JeremyRand** [comment]
Can you post this in the namecoin/namecore repo?

**Comment by cassiniNMC** [comment]
Oops, had forgotten our repo workflow.
