### ISSUE TITLE
Weird ASM encoding issue

### ISSUE THREAD

**Issue by brandonrobertz** [domob1812/namecore#8]
Hi, I may be totally off base here, but I'm running into a strange ASM encoding issue for the name_firstupdate script:

        {
            "value" : 0.01000000,
            "n" : 1,
            "scriptPubKey" : {
                "nameOp" : {
                    "op" : "name_firstupdate",
                    "name" : "AAA",
                    "value" : "AAA",
                    "rand" : "b2fcc738e6663deafa452e13af90fa420d0fc973"
                },
                "asm" : "OP_NAME_FIRSTUPDATE 4276545 b2fcc738e6663deafa452e13af90fa420d0fc973 4276545 OP_2DROP OP_2DROP OP_DUP OP_HASH160 a3290828f90dea7efd2b2493e01d5ed5e1374d6b OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "520341414114b2fcc738e6663deafa452e13af90fa420d0fc973034141416d6d76a914a3290828f90dea7efd2b2493e01d5ed5e1374d6b88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "mvPfbGSc2SHXF1K9YS2vfocMuAmhPqgHPQ"
                ]
            }
        }

I can't figure out why, but on some names, like the one above (`AAA`), the ASM representation for the name and value is a number of some kind. In this case it's `4276545`. The decoded JSON version is correct, though. Any thoughts on why this may be happening? Is this part of the protocol or encoding that I'm unaware of?

CONTEXT. I'm creating the transaction like this:

    name_new AAA
    # RESULT: [ "06e4266ad3cadffc67ffcfddb7caed9b38540124e69f3305de19249b4a95d222", "b2fcc738e6663deafa452e13af90fa420d0fc973" ]
    # GENERATE COINS, then:
    name_firstupdate AAA b2fcc738e6663deafa452e13af90fa420d0fc973 06e4266ad3cadffc67ffcfddb7caed9b38540124e69f3305de19249b4a95d222 AAA
    # RESULT 82b263a1af58a1705aa9b0c60f65d7b75f8ddb9442786849679812fdfb923d38

PS: Should issues be filed here or namecoin/namecore ?

**Comment by brandonrobertz** [comment]
The reference namecoind does something different, so I don't know what this is supposed to look like to begin with:

            "scriptPubKey" : {
                "nameOp" : {
                    "op" : "name_firstupdate",
                    "name" : "AAA",
                    "rand" : "5f9eaefbe582518700",
                    "value" : "AAA"
                },
                "asm" : "NAME_OPERATION OP_DUP OP_HASH160 158359f6f014a1941f1db949e58370f2fe9b20bb OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "5203414141095f9eaefbe582518700034141416d6d76a914158359f6f014a1941f1db949e58370f2fe9b20bb88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "mhUhqYEqUhFzDUVhhRnSQ9Aw8oxNE65yUA"
                ]
            }
        },

**Comment by domob1812** [comment]
I never bothered to look at the details of the `asm` encoding - but I guess that short values (e. g., up to 4 bytes?) are interpreted as numbers, and only longer ones output as hex.  (Note that 65*256^2+65*256+65=4,276,545!)

The old client (it is not really a "reference implementation" anymore, since a good chunk of hashing power already uses Namecoin Core) simply stripped off the name script prefix completely, that's why you do not see the value in it.

What are you trying to do with the `asm` field?

**Comment by brandonrobertz** [comment]
I'm porting bitcore to namecoin and am using output from namecore to build compliance tests. I ran into this in my script asm -> raw tests. I'm mostly just making sure that this isn't some kind of intentional encoding that I need to code around.

**Comment by domob1812** [comment]
Ok, I see.  As far as I'm aware, there are no intentional changes to the `asm` encoding.  Also note that I *think* that others are/were working on porting Bitcore as well - @JeremyRand, @phelix?

**Comment by brandonrobertz** [comment]
Okay, thanks for the info about `asm`. Great work on Namecoin Core, by the way.

I'm almost done with porting it over, so I hope nobody has already done the work. The only thing I could find online was an outdated gist with network values and a couple Reddit posts with no clear indication.

**Comment by brandonrobertz** [comment]
Also, you're right about the conversion to number. Here's the code responsible.

    namespace {
    inline std::string ValueString(const std::vector<unsigned char>& vch)
    {
        if (vch.size() <= 4)
            return strprintf("%d", CScriptNum(vch, false).getint());
        else
            return HexStr(vch);
    }
    } // anon namespace
